### ISSUE TITLE
Analyzer improvements

### ISSUE THREAD

**Issue by armanddidierjean** [aeecleclair/Titan#210]
Enable stricter analysis, add:
```
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
```
